import {
  AcademicClass,
  AccountVerificationCode,
  AdminBroadcast,
  Answer,
  DuelAnswer,
  DuelMatch,
  DuelMatchQuestion,
  DuelProgress,
  DuelScoreEvent,
  Notification,
  Question,
  QuizSession,
  QuizSessionQuestion,
  Subject,
  User,
} from '../mvp/entities';
import {
  ArenaCompetition,
  ArenaParticipantAnswer,
  ArenaParticipantMessage,
  ArenaParticipantRegistration,
  ArenaParticipantScoreAdjustment,
  ArenaRound,
} from '../arena/arena.entities';
import { Sponsor } from '../sponsors/sponsor.entity';
import {
  Assignment,
  ContestSession,
  CorrespondenceMessage,
  CorrespondenceThread,
  CorrespondenceVote,
  Letter,
  ModerationCase,
} from '../correspondence/correspondence.entities';
import { StudentDailyRecommendation } from '../student-insights/student-daily-recommendation.entity';
import { Chapter, TutorConversation, TutorMessage } from '../learning/learning.entities';

export const databaseEntities = [
  AcademicClass,
  Subject,
  User,
  AccountVerificationCode,
  Question,
  QuizSession,
  QuizSessionQuestion,
  Answer,
  DuelMatch,
  DuelMatchQuestion,
  DuelProgress,
  DuelAnswer,
  Notification,
  AdminBroadcast,
  DuelScoreEvent,
  ArenaCompetition,
  ArenaParticipantRegistration,
  ArenaRound,
  ArenaParticipantAnswer,
  ArenaParticipantMessage,
  ArenaParticipantScoreAdjustment,
  Sponsor,
  ContestSession,
  Letter,
  Assignment,
  CorrespondenceThread,
  CorrespondenceMessage,
  CorrespondenceVote,
  ModerationCase,
  StudentDailyRecommendation,
  Chapter,
  TutorConversation,
  TutorMessage,
];
