import {
  AcademicClass,
  AdminBroadcast,
  Answer,
  DuelAnswer,
  DuelMatch,
  DuelMatchQuestion,
  DuelProgress,
  DuelScoreEvent,
  Notification,
  Question,
  QuizSession,
  QuizSessionQuestion,
  Subject,
  User,
} from '../mvp/entities';
import {
  ArenaCompetition,
  ArenaParticipantAnswer,
  ArenaParticipantMessage,
  ArenaParticipantRegistration,
  ArenaParticipantScoreAdjustment,
  ArenaRound,
} from '../arena/arena.entities';
import { Sponsor } from '../sponsors/sponsor.entity';

export const databaseEntities = [
  AcademicClass,
  Subject,
  User,
  Question,
  QuizSession,
  QuizSessionQuestion,
  Answer,
  DuelMatch,
  DuelMatchQuestion,
  DuelProgress,
  DuelAnswer,
  Notification,
  AdminBroadcast,
  DuelScoreEvent,
  ArenaCompetition,
  ArenaParticipantRegistration,
  ArenaRound,
  ArenaParticipantAnswer,
  ArenaParticipantMessage,
  ArenaParticipantScoreAdjustment,
  Sponsor,
];